# Generated by Django 5.1 on 2024-10-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetour',
            name='tour_type',
            field=models.CharField(choices=[('group', 'Групповой'), ('individual', 'Индивидуальный')], default=1, max_length=20, verbose_name='Тип тура'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regiontour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
