# Generated by Django 5.0.6 on 2024-09-23 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_booking_user'),
        ('user', '0002_alter_myuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tour.booking'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='favorite_tours',
            field=models.ManyToManyField(blank=True, related_name='users', to='tour.tour'),
        ),
    ]
