# Generated by Django 5.1 on 2024-10-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Обычный пользователь'), (2, 'Менеджер'), (3, 'Консультант'), (4, 'Администратор'), (5, 'Автор туру')], default=1, verbose_name='Роль пользователя'),
        ),
    ]
